# Generated by Django 5.2.4 on 2025-07-29 02:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='NIF/Contribuinte')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_alerta_estoque', models.PositiveIntegerField(default=10, help_text='Quando o estoque de um produto for igual ou inferior a este valor, será mostrado um alerta.', verbose_name='Limite para Alerta de Estoque Baixo')),
                ('email_remetente', models.EmailField(blank=True, help_text='O endereço de email que será usado para enviar as faturas e guias (ex: seu.email@gmail.com).', max_length=255, verbose_name='Email de Envio')),
                ('password_remetente', models.CharField(blank=True, help_text='A palavra-passe de aplicação de 16 caracteres gerada pelo seu provedor de email (ex: Gmail).', max_length=255, verbose_name='Password de Aplicação do Email')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='DadosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logotipo')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('nif', models.CharField(max_length=50, verbose_name='NIF')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('dados_pagamento', models.TextField(help_text='Ex: IBAN, conta bancária, etc.', verbose_name='Dados de Pagamento')),
            ],
            options={
                'verbose_name': 'Dados da Empresa',
                'verbose_name_plural': 'Dados da Empresa',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('calibre', models.CharField(blank=True, max_length=50, verbose_name='calibre')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('unidade_medida', models.CharField(choices=[('ton', 'Tonelada'), ('m3', 'Metro Cúbico'), ('un', 'Unidade')], default='ton', max_length=3, verbose_name='unidade de medida')),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='estoque atual')),
                ('preco_por_unidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço por unidade')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='data de emissão')),
                ('numero_fatura', models.CharField(blank=True, max_length=50, unique=True, verbose_name='número da fatura')),
                ('paga', models.BooleanField(default=False, verbose_name='paga')),
                ('taxa_igv', models.DecimalField(decimal_places=2, default=17.0, max_digits=5, verbose_name='Taxa IGV (%)')),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentagem de desconto (ex: 5 para 5%)', max_digits=5, verbose_name='desconto (%)')),
                ('adiantamento', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor do adiantamento em euros', max_digits=10, verbose_name='adiantamento (€)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.cliente', verbose_name='cliente')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
            },
        ),
        migrations.CreateModel(
            name='GuiaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='data de emissão')),
                ('numero_guia', models.CharField(blank=True, max_length=50, unique=True, verbose_name='número da guia')),
                ('morada_carga', models.CharField(help_text='Local onde os bens são carregados.', max_length=255, verbose_name='morada de carga')),
                ('morada_descarga', models.CharField(help_text='Local onde os bens são descarregados.', max_length=255, verbose_name='morada de descarga')),
                ('matricula_veiculo', models.CharField(blank=True, max_length=50, verbose_name='matrícula do veículo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.cliente', verbose_name='cliente')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Guia de Transporte',
                'verbose_name_plural': 'Guias de Transporte',
                'ordering': ['-data_emissao', '-numero_guia'],
            },
        ),
        migrations.CreateModel(
            name='ItemGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantidade')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='stock.guiatransporte')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'Item da Guia',
                'verbose_name_plural': 'Itens da Guia',
            },
        ),
        migrations.CreateModel(
            name='ItemFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='quantidade')),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço unitário')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='stock.fatura')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produto', verbose_name='produto')),
            ],
        ),
    ]
