# Generated by Django 5.2.4 on 2025-07-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('calibre', models.CharField(blank=True, max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('unidade_medida', models.CharField(choices=[('ton', 'Tonelada'), ('m3', 'Metro Cúbico'), ('un', 'Unidade')], default='ton', max_length=3)),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('preco_por_unidade', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
