# Generated by Django 5.2.4 on 2025-07-21 22:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='NIF/Contribuinte')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='calibre',
            field=models.CharField(blank=True, max_length=50, verbose_name='calibre'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_atual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='estoque atual'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_por_unidade',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço por unidade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('ton', 'Tonelada'), ('m3', 'Metro Cúbico'), ('un', 'Unidade')], default='ton', max_length=3, verbose_name='unidade de medida'),
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='data de emissão')),
                ('numero_fatura', models.CharField(blank=True, max_length=50, unique=True, verbose_name='número da fatura')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='valor total')),
                ('paga', models.BooleanField(default=False, verbose_name='paga')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.cliente', verbose_name='cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='stock.fatura')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produto', verbose_name='produto')),
            ],
        ),
    ]
