# Generated by Django 5.2.4 on 2025-07-29 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiatransporte',
            name='cliente',
        ),
        migrations.AddField(
            model_name='guiatransporte',
            name='fatura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guia_transporte', to='stock.fatura', verbose_name='fatura de origem'),
        ),
    ]
