# Generated by Django 5.2.4 on 2025-07-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_cliente_alter_produto_calibre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='fatura',
            name='taxa_igv',
            field=models.DecimalField(decimal_places=2, default=17.0, max_digits=5, verbose_name='Taxa IGV (%)'),
        ),
    ]
