# Generated by Django 5.2.4 on 2025-07-29 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_guiatransporte_cliente_guiatransporte_fatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiatransporte',
            name='fatura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guia_transporte', to='stock.fatura', verbose_name='fatura de origem'),
        ),
    ]
