# Generated by Django 5.2.4 on 2025-07-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_guiatransporte_fatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_drive_folder_id', models.CharField(blank=True, help_text='Opcional. Cole aqui o ID da pasta do Google Drive onde os backups serão guardados.', max_length=255, verbose_name='ID da Pasta no Google Drive')),
                ('credentials_file', models.FileField(help_text='Carregue aqui o ficheiro JSON da conta de serviço do Google que descarregou.', upload_to='configs/', verbose_name='Ficheiro de Credenciais (JSON)')),
                ('last_backup_status', models.CharField(default='Nunca executado', editable=False, max_length=50, verbose_name='Estado do Último Backup')),
                ('last_backup_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data do Último Backup')),
            ],
            options={
                'verbose_name': 'Configuração de Backup',
                'verbose_name_plural': 'Configuração de Backup',
            },
        ),
    ]
