# Generated by Django 5.2.4 on 2025-07-25 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_fatura_valor_total_fatura_taxa_igv'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 25, 3, 23, 46, 273264, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
