# Generated by Django 5.2.4 on 2025-07-25 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_fatura_atualizado_em_fatura_criado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logotipo')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('nif', models.CharField(max_length=50, verbose_name='NIF')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('dados_pagamento', models.TextField(help_text='Ex: IBAN, conta bancária, etc.', verbose_name='Dados de Pagamento')),
            ],
            options={
                'verbose_name': 'Dados da Empresa',
                'verbose_name_plural': 'Dados da Empresa',
            },
        ),
        migrations.AddField(
            model_name='fatura',
            name='utilizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
