# Generated by Django 5.2.4 on 2025-07-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_backupconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupconfig',
            name='credentials_file',
        ),
        migrations.RemoveField(
            model_name='backupconfig',
            name='google_drive_folder_id',
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='recipient_email',
            field=models.EmailField(default='backup@exemplo.com', help_text='O endereço de email para onde os ficheiros de backup serão enviados.', max_length=254, verbose_name='Email de Destino para Backups'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backupconfig',
            name='last_backup_status',
            field=models.CharField(default='Nunca executado', editable=False, max_length=255, verbose_name='Estado do Último Backup'),
        ),
    ]
