# Generated by Django 5.2.4 on 2025-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_backupconfig_credentials_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupconfig',
            name='schedule',
            field=models.CharField(choices=[('MANUAL', 'Manual (apenas através do botão no admin)'), ('DIARIO', 'Diário'), ('SEMANAL', 'Semanal')], default='MANUAL', help_text='Define a frequência com que os backups automáticos devem ser executados.', max_length=10, verbose_name='Frequência do Backup Automático'),
        ),
    ]
