# Generated by Django 5.2.4 on 2025-07-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_dadosempresa_fatura_utilizador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='fatura',
            options={'verbose_name': 'Fatura', 'verbose_name_plural': 'Faturas'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='fatura',
            name='adiantamento',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor do adiantamento em euros', max_digits=10, verbose_name='adiantamento (€)'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentagem de desconto (ex: 5 para 5%)', max_digits=5, verbose_name='desconto (%)'),
        ),
    ]
