# Generated by Django 5.2.4 on 2025-07-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_cliente_options_alter_fatura_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_alerta_estoque', models.PositiveIntegerField(default=10, help_text='Quando o estoque de um produto for igual ou inferior a este valor, será mostrado um alerta.', verbose_name='Limite para Alerta de Estoque Baixo')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
