# Generated by Django 5.2.4 on 2025-07-28 05:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_configuracao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfatura',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço unitário'),
        ),
        migrations.AlterField(
            model_name='itemfatura',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='quantidade'),
        ),
        migrations.CreateModel(
            name='GuiaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='data de emissão')),
                ('numero_guia', models.CharField(blank=True, max_length=50, unique=True, verbose_name='número da guia')),
                ('morada_carga', models.CharField(help_text='Local onde os bens são carregados.', max_length=255, verbose_name='morada de carga')),
                ('morada_descarga', models.CharField(help_text='Local onde os bens são descarregados.', max_length=255, verbose_name='morada de descarga')),
                ('matricula_veiculo', models.CharField(blank=True, max_length=50, verbose_name='matrícula do veículo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.cliente', verbose_name='cliente')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Guia de Transporte',
                'verbose_name_plural': 'Guias de Transporte',
                'ordering': ['-data_emissao', '-numero_guia'],
            },
        ),
        migrations.CreateModel(
            name='ItemGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantidade')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='stock.guiatransporte')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'Item da Guia',
                'verbose_name_plural': 'Itens da Guia',
            },
        ),
    ]
