# Generated by Django 5.2.4 on 2025-07-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_itemfatura_preco_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='email_remetente',
            field=models.EmailField(blank=True, help_text='O endereço de email que será usado para enviar as faturas e guias (ex: seu.email@gmail.com).', max_length=255, verbose_name='Email de Envio'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='password_remetente',
            field=models.CharField(blank=True, help_text='A palavra-passe de aplicação de 16 caracteres gerada pelo seu provedor de email (ex: Gmail).', max_length=255, verbose_name='Password de Aplicação do Email'),
        ),
    ]
