# Generated by Django 5.2.4 on 2025-07-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_backupconfig_schedule'),
        ('stock', '0009_configuracao_email_remetente_and_more'),
    ]

    operations = [
    ]
