# Generated by Django 5.2.4 on 2025-07-30 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_merge_20250730_0149'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
    ]
